
#端口设置
server:
  port: 8080

#连接数据库配置
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

#日志设置

logging:
  level:
    root: DEBUG

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.springboottest1.entity  # 注意：对应实体类的路径


# 应该以什么样的路径来访问静态资源,这表示只有静态资源的访问路径为/static/ 时才会处理
spring.mvc.static-path-pattern: /static/**

#用于告诉Spring Boot应该在何处查找静态资源文件,查找文件时会依赖于配置的先后顺序依次进行
spring.resources.static-locations:
  classpath:/static
  classpath:/public
  classpath:/resources
  classpath:/META-INF/resources